### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$$')

### ISSUE THREAD

**Issue by KyleFontenot** [pd4d10/bytemd#14]
Error when using the example code in Svelte:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$$')
    at init (index.mjs:312:46)
    at new Editor (index.mjs:3575:5)
```
I'm assuming it isn't updated for svelte but I can't tell

**Comment by 0gust1** [comment]
duplicate of https://github.com/bytedance/bytemd/issues/11
